### ISSUE TITLE
Mais dados no release name.

### ISSUE THREAD

**Issue by alangregory** [gabrielbdsantos/BJ_Couchpotato#2]
Qual a possibilidade de adicionar mais dados ao nome da release para filtros.
Exemplo: Dual Áudio.
Motivo: Baixar somente release com uma trilha de áudio em pt-br.

**Comment by gabrielbdsantos** [comment]
Quando estava fazendo o plugin, eu tentei fazer isso.
Na época, isso quebrava o reconhecimento do nome do filme. O CouchPotato, tentava enquadrar o Dual-Áudio/Legendado/Dublado como qualidade do filme ou outro parâmetro.

Mas isso foi há bastante tempo. Talvez com novos commits da parte deles isso tenha mudado.
Vamos ver se já é possível.

**Comment by gabrielbdsantos** [comment]
Foi possível fazer isso. O commit 7fee3e4feaa65911309adb2669e5f4f59f14f1ae já possui a nova funcionalidade.

**Comment by alangregory** [comment]
Confirmado funcionando. Obrigado.
